version: '3.7'

services:
  web:
    build:
      context: .
    image: spotlight
    env_file:
      - .env
    volumes:
      - .:/spotlight/engine
    ports:
      - 3000:3000
    depends_on:
      - chrome
      - db_migrate
      - solr
    stdin_open: true
    tty: true
    networks:
      - spotlight

  db_migrate:
    image: spotlight
    env_file:
      - .env
    entrypoint: sh -c '/spotlight/engine/bin/db-migrate-seed.sh'
    depends_on:
      - postgres
    volumes:
      - .:/spotlight/engine
    networks:
      - spotlight

  postgres:
    image: bitnami/postgresql:12.6.0
    restart: always
    environment:
      - POSTGRES_USER=spotlight_user
      - POSTGRES_PASSWORD=spotlight_password
      - POSTGRES_DB=spotlight
      - POSTGRES_HOST_AUTH_METHOD=trust
    # ports:
    #   - 5432:5432
    volumes:
      - spotlight_db:/var/lib/postgresql/data
    networks:
      - spotlight

  solr:
    image: grumble/solr:d46c663533972dacbcfd0d591a5995daa6d737ff
    env_file:
      - .env
    ports:
      - 8983:8983
    volumes:
      - spotlight_solr:/opt/solr/server/solr
      - ./lib/generators/spotlight/templates/solr/config:/opt/custom/spotlightset
    networks:
      - spotlight

  chrome:
    image: selenium/standalone-chrome:3.141
    networks:
      - spotlight

volumes:
  spotlight_db:
  spotlight_redis:
  spotlight_solr:

networks:
  spotlight:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-spotlight
